### PR TITLE
Fix Pull Request Template Spelling and Layout Issues

### LINKED ISSUE #45: Spelling error in pull request template
Spelling mistake in the pull request template

affects:
InsanityNetwork/InsanityBot/master@035510b (latest)
InsanityNetwork/InsanityBot/2.0.0-dev@2c0c448 (latest)

### PR DESCRIPTION
**Pull request by akiraveliara**
**What issues are fixed in this Pull Request**: #45

### CODE REVIEW

**Review by TrainerGamer — DISMISSED** [review]
Please add `:`'s and put the notes on new lines

**Comment by akiraveliara** [comment]
oh well, speaking of pull request template, there are no :s in the default template

**Comment by TrainerGamer** [comment]
It is in order to keep it in-keeping with the issue templates

**Comment by akiraveliara** [comment]
I do not think this applies here since the issue template lines are headers/titles, unlike here

**Review by TrainerGamer — CHANGES_REQUESTED** [review]
As previously requested, please make the descriptions on new lines

**Comment by akiraveliara** [comment]
That is not required by the [Contribution Guidelines](https://github.com/InsanityNetwork/InsanityBot/blob/master/CONTRIBUTING.md)

**Comment by TrainerGamer** [comment]
I don't quite know if you understand what I mean...
I would like it to have the part after the `:`/bold text on the new line so it is like the issue templates.

**Comment by akiraveliara** [comment]
Yes, i understand what you mean: given how GitHub handles issue formatting I do not see this being a justifiable requirement at all. Issue links, unlike descriptions like in the issue templates, are very short and therefore do not justify a requirement of there being a newline.

**Comment by TrainerGamer** [comment]
Alright, in that case I'll merge the changes

**Review by TrainerGamer — APPROVED** [review]

**Pull request merged**
